version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio_jl
    labels:
      - "traefik.enable=true"

      # Redirection HTTP -> HTTPS
      - "traefik.http.routers.portfolio-http.rule=Host(`jonathanlore.fr`) || Host(`www.jonathanlore.fr`)"
      - "traefik.http.routers.portfolio-http.entrypoints=http"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"

      # Site principal sur HTTPS avec redirection www -> non-www
      - "traefik.http.routers.portfolio-https.rule=Host(`jonathanlore.fr`) || Host(`www.jonathanlore.fr`)"
      - "traefik.http.routers.portfolio-https.entrypoints=websecure"
      - "traefik.http.routers.portfolio-https.tls=true"
      - "traefik.http.routers.portfolio-https.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-https.middlewares=redirect-to-non-www"

      # Définition du service
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      # Middleware : www -> non-www
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"

      # Middleware : HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

    networks:
      - web

networks:
  web:
    external: true
