version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio_jl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jonathanlore.fr`) || Host(`www.jonathanlore.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      # Add redirect middlewares for http and https
      - "traefik.http.routers.portfolio.middlewares=redirect-http-www@file,redirect-https-www@file"
    networks:
      - web

networks:
  web:
    external: true
