version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio_jl
    labels:
      - "traefik.enable=true"

      # Redirection HTTP -> HTTPS
      - "traefik.http.routers.portfolio-http.rule=Host(`jonathanlore.fr`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"

      # Site principal sur HTTPS
      - "traefik.http.routers.portfolio-https.rule=Host(`jonathanlore.fr`)"
      - "traefik.http.routers.portfolio-https.entrypoints=websecure"
      - "traefik.http.routers.portfolio-https.tls=true"
      - "traefik.http.routers.portfolio-https.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

      # Redirection www vers non-www
      - "traefik.http.routers.www-portfolio.rule=Host(`www.jonathanlore.fr`)"
      - "traefik.http.routers.www-portfolio.entrypoints=web"
      - "traefik.http.routers.www-portfolio.middlewares=redirect-to-non-www"

      # Middleware pour rediriger www vers non-www
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$1"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"

      # Middleware pour rediriger HTTP vers HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

    networks:
      - web

networks:
  web:
    external: true
