version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio_jl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jonathanlore.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

    networks:
      - web

networks:
  web:
    external: true
